### ISSUE TITLE
Passwords Opens Manage Accounts

### ISSUE THREAD

**Issue by roshanravan** [WSTxda/Google-Shortcuts-Launcher#2]
after New Update tested with two devices the Shortcut for Passwords opens device Users & Accounts or Manage Accounts Settings

**Comment by WSTxda** [comment]
oh, it's happening because in Android 12 or higher, google passwords is moved to this screen.

**Comment by roshanravan** [comment]
but the previous version was working correctly!
I can see in the Chrome/Settings/Password Manager. there is an option for "Add Shortcut to get here quicker, add Google Password Manager to your home screen" and the Shortcut works, there is just a popup to select which account Because I have two Google Account in my device and it goes to the password manager

**Comment by WSTxda** [comment]
it's refer this commit c84e399

use settings screen seems to be more secure and comfortable, since you don't need to be logged into another browser with your account, in addition to having more options for passwords such as autofill.

i can try use both solutions soon.

**Comment by WSTxda** [comment]
@roshanravan check new update, sorry delay 🥲

**Comment by KelvinCrag** [comment]
@WSTxda Now the shortcut opens the website in the default browser. I was thinking it was supposed to open its Google activity launcher.
